properties([
    parameters([
        string(name: 'GIT_REF', defaultValue: 'feature/jenkins', description: 'Branch, tag or commit SHA to build')
    ])
])

pipeline {
    agent none

    environment {
        POSTGRES_USER = 'postgres'
        POSTGRES_PASSWORD = 'postgres'
        POSTGRES_DB = 'postgres'
        POSTGRES_HOST = '172.17.0.1'
        DATABASE_URL = 'postgres://postgres:postgres@172.17.0.1:5432'
    }

    stages {
        stage('Start Postgres') {
            agent any
            steps {
                sh '''
                  docker run --name jenkins-postgres -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres -d postgres:15
                  for i in {1..60}; do
                    docker exec jenkins-postgres pg_isready -U postgres && break
                    sleep 1
                  done
                '''
            }
        }

        stage('Matrix Pipeline') {
            matrix {
                axes {
                    axis {
                        name 'RUBY_VERSION'
                        values '3.4', '3.3'
                    }
                }
                agent {
                    docker {
                        image "ruby:${RUBY_VERSION}"
                    }
                }
                stages {
                    stage('Checkout') {
                        steps {
                            deleteDir()
                            checkout([
                                $class: 'GitSCM',
                                branches: [[name: params.GIT_REF]],
                                userRemoteConfigs: [[url: 'https://github.com/RodrigoMNardi/netdef-ci-github-app.git']]
                            ])
                        }
                    }
                    stage('01 - Install bundler') {
                        steps {
                            sh 'gem install bundler -v 2.7.1'
                        }
                    }
                    stage('02 - Install gems') {
                        steps {
                            sh 'bundle install'
                        }
                    }
                    stage('03 - Create DB') {
                        environment {
                            RACK_ENV = 'test'
                        }
                        steps {
                            sh '''
                              cp database_template.yml config/database.yml
                              cp db/schema.rb db/schema.rb.bak
                              bundle exec rake db:migrate:reset
                              if ! cmp db/schema.rb db/schema.rb.bak >/dev/null 2>&1; then
                                echo 'Your db/schema.rb differs from the schema generated by the migrations.'
                                echo 'Use "DATABASE=migrations bundle exec rake db:migrate:reset" to regenerate the schema.'
                                diff db/schema.rb db/schema.rb.bak
                                exit 1
                              fi
                            '''
                        }
                    }
                    stage('04 - Unit Tests') {
                        environment {
                            DATABASE_URL = 'postgres://postgres:postgres@172.17.0.1:5432'
                        }
                        steps {
                            sh 'sed -i \'s/localhost/172.17.0.1/g\' config/database.yml'
                            sh 'cp config_template.yml config.yml || true'
                            sh 'bundle exec rspec'
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            sh 'docker rm -f jenkins-postgres || true'
            echo 'Pipeline done'
        }
        success {
            echo 'SUCCESS!'
        }
        failure {
            echo '❌ FAILURE!'
        }
    }
}
