pipeline {
    agent {
        docker {
            image 'ruby:3.4'
            args '--network jenkins-net'
        }
    }

    environment {
        POSTGRES_USER = 'postgres'
        POSTGRES_PASSWORD = 'postgres'
        POSTGRES_DB = 'postgres'
        POSTGRES_HOST = 'postgres'
        DATABASE_URL = 'postgres://postgres:postgres@postgres:5432'
    }

    stages {
        stage('Prepare Network') {
            steps {
                sh 'docker network create jenkins-net || true'
            }
        }

        stage('Checkout') {
            steps {
                deleteDir()
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: 'master']], // Tente main se master não existir
                    userRemoteConfigs: [[url: 'https://github.com/RodrigoMNardi/netdef-ci-github-app.git']]
                ])
            }
        }

        stage('Start Postgres') {
            steps {
                sh '''
                  docker run --name jenkins-postgres --network jenkins-net -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres -d postgres:15
                  sleep 15
                '''
            }
        }

        stage('Ruby Pipeline') {
            stages {
                stage('Install bundler') {
                    steps {
                        sh 'gem install bundler -v 2.7.1'
                    }
                }
                stage('Install gems') {
                    steps {
                        sh 'bundle install'
                    }
                }
                stage('Create DB') {
                    environment {
                        RACK_ENV = 'test'
                    }
                    steps {
                        sh '''
                          cp database_template.yml config/database.yml
                          cp db/schema.rb db/schema.rb.bak
                          bundle exec rake db:migrate:reset
                          if ! cmp db/schema.rb db/schema.rb.bak >/dev/null 2>&1; then
                            echo 'Your db/schema.rb differs from the schema generated by the migrations.'
                            echo 'Use "DATABASE=migrations bundle exec rake db:migrate:reset" to regenerate the schema.'
                            diff db/schema.rb db/schema.rb.bak
                            exit 1
                          fi
                        '''
                    }
                }
                stage('Unit Tests') {
                    steps {
                        sh 'cp config_template.yml config.yml || true'
                        sh 'bundle exec rspec'
                    }
                }
            }
        }
    }

    post {
        always {
            sh 'docker rm -f jenkins-postgres || true'
            sh 'docker network rm jenkins-net || true'
            echo 'Pipeline done'
        }
        success {
            echo 'SUCCESS!'
        }
        failure {
            echo '❌ FAILURE!'
        }
    }
}
